name: apk_manager
description: A new Flutter project.
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  provider: ^6.0.5
  cloud_firestore: ^4.8.1
  url_launcher: ^6.1.6
  flutter_launcher_icons: ^0.13.1
  firebase_messaging: ^14.6.3
  external_app_launcher: ^3.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  http: ^1.2.1
  path_provider: ^2.1.3
  open_filex: ^4.3.2
  equatable: ^2.0.5
  google_sign_in: ^5.3.0
  flutter_svg: ^1.0.3
  package_info: ^2.0.2
  shorebird_code_push: ^1.1.3
  sentry_flutter: ^7.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_icons:
  android: "launcher_icon"
  # android: false
  ios: false
  image_path: "assets/images/launcher_icon.png"
  remove_alpha_ios: true

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
